### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by hammaazarok** [ogagaoghene/v1-mobile-web-app#12]
#11 the line 3 is not in correct flow you can move it to 17 to correct the flow

**Comment by ogagaoghene** [comment]
Okay thanks.  I will move it to the exact point where it is reachable.

**Comment by ogagaoghene** [comment]
Yeah. You are right, It should be the last statement to execute or be invoked

**Comment by ogagaoghene** [comment]
Thanks
